# C3-PRO Jazzy config
module: C3PRO

author: C3-PRO
author_url:  http://c3-pro.chip.org

root_url:    http://c3-pro.github.io/c3-pro-ios-framework
github_url:  https://github.com/c3-pro/c3-pro-ios-framework.git

theme: fullwidth
readme: README.md
#documentation: Sources/*/README.md
custom_categories:
  - name: Common
    children:
    - C3Error
    - C3PROFHIRVersion

  - name: Questionnaire
    children:
    - QuestionnaireController
    - QuestionnairePromise
    - QuestionnaireGroupPromise
    - QuestionnaireQuestionPromise
    - ConditionalOrderedTask
    - ResultRequirement
    - GroupCharacteristic

  - name: Study Intro
    children:
    - StudyIntroConfiguration
    - StudyIntroCollectionViewController
    - StudyIntroItem
    - StudyIntroWelcomeItem
    - StudyIntroHTMLItem
    - StudyIntroVideoItem

  - name: Eligibility & Consent
    children:
    - ConsentController
    - ConsentTask
    - ConsentTaskOptions
    - ConsentResult
    - ConsentSigningCallback
    - C3UserDidConsentNotification
    - C3UserDidDeclineConsentNotification
    - C3ConsentResultKey
    - EligibilityRequirement
    - EligibilityStatusViewController
    - EligibilityCheckViewController
    - GroupCharacteristic
    - Contract
    - ContractTerm
    - kContractTermConsentSectionExtension
    - kContractTermConsentSectionType

  - name: HealthKit & CoreData
    children:
    - ActivityReporter
    - ActivityCollector
    - HealthKitReporter
    - CoreMotionReporter
    - CoreMotionActivityInterpreter
    - CoreMotionStandardActivityInterpreter
    - CoreMotionActivityType
    - CoreMotionActivitySum
    - CoreMotionActivityInterpretation
    - ActivityReport
    - ActivityReportPeriod
    - CoreMotionActivity
    - InterpretedCoreMotionActivity
    - HealthKitTypes
    - HKHealthStore
    - HKQuantity
    - HKQuantitySample
    - HKQuantityType

  - name: Data Queue
    children:
    - QueuedResource
    - DataQueue
    - EncryptedDataQueue
    - EncryptedDataQueueDelegate
    - EncryptedJSONRequestHandler
    - OAuth2DynRegAppStore

  - name: System Services
    children:
    - SystemService
    - SystemServicePermissioner
    - SystemPermissionStep

  - name: Encryption
    children:
    - AESUtility
    - RSAUtility

  - name: De-Identifier
    children:
    - DeIdentifier
    - Geocoder
    - GeocoderAddressCallback
    - GeocoderPlacemarkCallback
    - GeocoderLocationCallback

  - name: View Controller
    children:
    - WebViewController
    - PDFViewController
    - PermissionRequestTableViewController
    - SystemPermissionTableViewController
    - SystemPermissionStepViewController

  - name: Table Cells & Views
    children:
    - BorderedButton
    - EligibilityCell
    - PermissionRequestTableViewCell
    - StudyIntroHTMLCell
    - StudyIntroVideoCell
    - StudyIntroWelcomeCell
